### ISSUE TITLE
i want to use the ZED stereo camzra to realize some function

### ISSUE THREAD

**Issue by kearcer** [mt-cly/Fisheye_getDistance_baseOn_OPENCV#1]
I want to use ZED camera to measuring the real-time road situation.and i want to measuring the real-time car speed in the road,Can you give me some advise about that ?Can you tell me weather i can realize it and which knowledge i need to learn.i just learn the python ,but the code on github are always C++,dear friend if you give me some advise i will very thank you.If some one want to help me please add my FB id 18751072631,Thank you for your listening.

**Comment by mt-cly** [comment]
> I want to use ZED camera to measuring the real-time road situation.and i want to measuring the real-time car speed in the road,Can you give me some advise about that ?Can you tell me weather i can realize it and which knowledge i need to learn.i just learn the python ,but the code on github are always C++,dear friend if you give me some advise i will very thank you.If some one want to help me please add my FB id 18751072631,Thank you for your listening.

Hi
Actually I writed that with python firstly, but the debug process is really difficulty. As you know, opencv-python is based on C++ module and just invoke those C++ interface. So if you realize with python, you may spend lots of time in debug cause the error usually happend in C++ layers and PDB would be unhelpful. 
So,   I still recommend that coding with C++. For reference materials, opencv has provided some sample codes which may help you to better understand.
