### ISSUE TITLE
The unit of square_size?

### ISSUE THREAD

**Issue by Chen414** [mt-cly/Fisheye_getDistance_baseOn_OPENCV#2]
Can you tell me the unit of the param square_size?

**Comment by mt-cly** [comment]
Hi, the quare_size is not specified. You can set it with any size you like, but update the board_width and board_height in the cfg file. The unit is centimeter (cm).

**Comment by Chen414** [comment]
> Hi, the quare_size is not specified. You can set it with any size you like, but update the board_width and board_height in the cfg file. The unit is centimeter (cm).

Thank you!!!!!
